#!/bin/sh
# $Id: create_release,v 1.2 2005/01/11 22:27:00 hamatoma Exp $
if [ -z $1 ] ; then
	echo "Aufruf: create_release VERSION"
	echo "Bsp: create_release 0.7.0"
	exit 1
fi
Version=$1
rm -f infobasar-*zip
cd ../..
Zip=infobasar-$Version.zip
zip -9ovn ".gz" infobasar/install/$Zip \
	infobasar/docu/* \
	infobasar/install/*.hma.gz \
	infobasar/install/*.txt \
	infobasar/install/licence \
	infobasar/install/*.pl \
	infobasar/install/ib_*.lst \
	infobasar/install/mk_arch \
	infobasar/install.php
cd infobasar
rm -f backup/$Zip
cp install/$Zip backup/$Zip
echo Datei readme.txt:
grep Version install/readme.txt