#!/bin/sh
if [ -z $1 ] ; then
	echo "Aufruf: mk_arch VERSION"
	echo "Bsp: mk_arch 0.5.3"
	exit 1
fi
rm -f infobasar-*hma*
Version=$1
name=infobasar-$Version.hma
perl tool/mk_arch.pl -v -a$name ib_install.lst
gzip -9 $name
name=infobasar-$Version-update.hma
perl tool/mk_arch.pl -v -a$name ib_update.lst
gzip -9 $name
